apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-maven-plugin-test.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "helm-maven-plugin-test.name" . }}
    helm.sh/chart: {{ include "helm-maven-plugin-test.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{.Values.component}}
    app.kubernetes.io/part-of: {{.Values.stack }}
    app.kubernetes.io/tier: {{.Values.tier }}
    app.kubernetes.io/stage: {{.Values.stage }}
    app.kubernetes.io/project: {{.Values.project }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "helm-maven-plugin-test.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "helm-maven-plugin-test.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: {{.Values.component}}
        app.kubernetes.io/part-of: {{.Values.stack }}
        app.kubernetes.io/tier: {{.Values.tier }}
        app.kubernetes.io/stage: {{.Values.stage }}
        app.kubernetes.io/project: {{.Values.project }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.probe.liveness.path }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.probe.readiness.path }}
              port: http
          env:
{{- with .Values.resources }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
{{- end }}
{{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name:
{{ toYaml .Values.imagePullSecret | indent 12 }}
{{- end }}
{{- if .Values.securityContext }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}