{{- if .Values.ingress.enabled -}}
{{- $fullName := include "helm-maven-plugin-test.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "helm-maven-plugin-test.name" . }}
    helm.sh/chart: {{ include "helm-maven-plugin-test.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{.Values.component}}
    app.kubernetes.io/part-of: {{.Values.stack }}
    app.kubernetes.io/tier: {{.Values.tier }}
    app.kubernetes.io/stage: {{.Values.stage }}
    app.kubernetes.io/project: {{.Values.project }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:

  rules:
    - http:
        paths:
        - backend:
            serviceName: {{ $fullName }}
            servicePort: http
          path: {{ .Values.ingress.path }}
{{- end }}
