apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-maven-plugin-test.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "helm-maven-plugin-test.name" . }}
    helm.sh/chart: {{ include "helm-maven-plugin-test.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{.Values.component}}
    app.kubernetes.io/part-of: {{.Values.stack }}
    app.kubernetes.io/tier: {{.Values.tier }}
    app.kubernetes.io/stage: {{.Values.stage }}
    app.kubernetes.io/project: {{.Values.project }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "helm-maven-plugin-test.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
